# Generated by Django 5.2.8 on 2025-12-02 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание фотографии'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='photos/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Избранное (показать на главной)'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название фотографии'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки'),
        ),
    ]
